---
tw:
  :consumer_key: 'roYA0OSPrAJfx6pEfKmcWGvXQ'
  :consumer_secret: 'kQv96SS27AVmPSDajuCLnnbo63ugM9aQD2csI8iOibFeuLUHtt'
  :access_token: '145575729-FtWR3rEUaQv68vZqL2wpMik8ffgRtZQo6xWqorkU'
  :access_token_secret: 'rVR0NFSb8fuLtiVdw8v8Ryrny2rkbQdDCm6GfBNYRJeoV'
